[workspace]
authors = ["Liam Pohlmann <liam.pohlmann@gmail.com>"]
channels = ["conda-forge"]
name = "kingfisher"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
debug = "cmake --workflow --preset build-debug"
dev = "cmake --workflow --preset dev"
release = "cmake --workflow --preset release"

[dependencies]
cmake = ">=4.4.4,<5"
ninja = ">=1.13.2,<2"
doxygen = ">=1.18.0,<2"
graphviz = ">=14.1.2,<15"
gtest = ">=1.18.0,<2"
fmt = ">=12.2.0,<13"

[feature.docs.dependencies]
sphinx = ">=8.2.3,<9"
sphinx_rtd_theme = ">=3.1.0,<4"
myst-parser = ">=5.1.0,<6"
breathe = ">=5.1.0,<6"
sphinxcontrib-bibtex = ">=2.7.0,<3"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinx-design = ">=0.7.0,<0.8"
sphinx-autobuild = ">=2025.8.25,<2026"

[feature.docs.tasks]
docs-doxygen = { cmd = "dot -c && mkdir -p _build/html && doxygen Doxyfile", cwd = "docs" }
docs = { cmd = "sphinx-build -b html -W --keep-going source _build/html", cwd = "docs", depends-on = ["docs-doxygen"] }
docs-serve = { cmd = "sphinx-autobuild source _build/html", cwd = "docs", depends-on = ["docs-doxygen"] }

[environments]
docs = ["docs"]
