[workspace]
authors = ["Liam Pohlmann <liam.pohlmann@gmail.com>"]
channels = ["conda-forge"]
name = "kingfisher"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
debug = "cmake --workflow --preset build-debug"
dev = "cmake --workflow --preset dev"
release = "cmake --workflow --preset release"

[dependencies]
cmake = ">=4.4.4,<5"
ninja = ">=1.13.2,<2"
doxygen = ">=1.18.0,<2"
graphviz = ">=14.1.2,<15"
gtest = ">=1.18.0,<2"
fmt = ">=12.2.0,<13"
